---
collections:
  - name: community.general
  - name: community.grafana
  - name: community.mysql  
  - name: community.docker 
  - name: community.zabbix
  - name: community.postgresql
  - name: ansible.posix
