---
- hosts: zabbix_agents
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Обновление пакетов и установка зависимостей
      apt:
        update_cache: yes
        name: "{{ item }}"
        state: present
      loop:
        - php
        - snmp
        - wget
        - mc
        - curl
        - nmap

    - name: Обновление пакетов и установка зависимостей
      apt:
        update_cache: yes

    - name: Загрузка пакета Zabbix Agent 6.4
      get_url:
        url: "https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb"
        dest: "/tmp/zabbix-release_6.4-1+ubuntu22.04_all.deb"

    - name: Установка пакета Zabbix 6.4
      apt:
        deb: "/tmp/zabbix-release_6.4-1+ubuntu22.04_all.deb"
      register: install_zabbix_agent
      ignore_errors: yes  # Игнорируем ошибки, если пакет уже установлен
    - name: Установка Zabbix агента
      apt:
        name: zabbix-agent
        state: present

    - name: Настройка Zabbix агента
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: 'Server=192.168.124.160'

    - name: Настройка Zabbix агента (добавление ServerActive)
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^# ServerActive='
        line: 'ServerActive=192.168.124.160'

    - name: Настройка Zabbix агента (Hostname)
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Hostname='
        line: 'Hostname={{ ansible_hostname }}'

    - name: Перезапуск Zabbix агента
      service:
        name: zabbix-agent
        state: restarted
# sudo -s
# wget https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb
# dpkg -i zabbix-release_6.4-1+ubuntu22.04_all.deb
# apt update
# apt install zabbix-agent
# systemctl restart zabbix-agent
# systemctl enable zabbix-agent