---
- hosts: zabbix_agents
  become: yes
  tasks:
    - name: Обновление пакетов и установка зависимостей
      apt:
        update_cache: yes

    - name: Добавление репозитория Zabbix
      apt_repository:
        repo: "deb http://repo.zabbix.com/zabbix/6.0/ubuntu $(lsb_release -cs) main"
        state: present
        filename: zabbix

    - name: Добавление ключа GPG для Zabbix репозитория
      apt_key:
        url: "https://repo.zabbix.com/zabbix-official-repo.key"
        state: present

    - name: Установка Zabbix агента
      apt:
        name: zabbix-agent
        state: present

    - name: Настройка Zabbix агента
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: 'Server=your_zabbix_server_ip'

    - name: Настройка Zabbix агента (добавление ServerActive)
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^# ServerActive='
        line: 'ServerActive=your_zabbix_server_ip'

    - name: Настройка Zabbix агента (Hostname)
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Hostname='
        line: 'Hostname={{ ansible_hostname }}'

    - name: Перезапуск Zabbix агента
      service:
        name: zabbix-agent
        state: restarted
