---
- hosts: zabbix_servers
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    serviceName: ZabbixPlatform
    serverIp: 192.168.124.160
    DBPassword: "S!uper_1P@ssw0rd@2023!"
  tasks:
    - name: Update system packages
      apt:
        update_cache: yes

    - name: Install depended packages for "{{ serviceName }}""
      apt:
        update_cache: yes
        name: "{{ item }}"
        state: present
      loop:
        - mariadb-server
        - mariadb-client
        - apache2
        - php
        - php-mysql
        - libapache2-mod-php
        - snmp
        - php-gd
        - php-xml
        - php-bcmath
        - php-mbstring
        - php-ldap
        - php-net-socket
        - wget
        - mc
        - curl
        - nmap

    - name: Download Zabbix 6.4
      get_url:
        url: "https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb"
        dest: "/tmp/zabbix-release_6.4-1+ubuntu22.04_all.deb"

    - name: Install Zabbix 6.4
      apt:
        deb: "/tmp/zabbix-release_6.4-1+ubuntu22.04_all.deb"
      register: install_zabbix_server
      ignore_errors: yes  # Игнорируем ошибки, если пакет уже установлен

    - name:  Update system packages
      apt:
        update_cache: yes

    - name: Install Zabbix server
      apt:
        name:
          - zabbix-server-mysql
          - zabbix-frontend-php
          - zabbix-apache-conf
          - zabbix-sql-scripts
          - zabbix-agent
        state: present


    - name: Install PyMySQL for Python 3
      apt:
        name: python3-pymysql
        state: present

    - name: DB creation (Unix socket)
      shell: |
        echo "CREATE DATABASE IF NOT EXISTS zabbix;" | mysql --user=root
      become: yes
      become_user: root

    - name: Create DB user (Unix socket)
      shell: |
        echo "CREATE USER IF NOT EXISTS 'zabbix'@'localhost' IDENTIFIED BY '{{ DBPassword }}'; GRANT ALL PRIVILEGES ON zabbix.* TO 'zabbix'@'localhost'; FLUSH PRIVILEGES;" | mysql --user=root
      become: yes
      become_user: root

    - name: Import DB Schema for Zabbix server
      shell: "zcat /usr/share/zabbix-sql-scripts/mysql/server.sql.gz | mysql -u zabbix -p'{{ DBPassword }}' zabbix"
      args:
        executable: /bin/bash


    - name: Setup Zabbix server
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: '^# DBPassword='
        line: 'DBPassword={{ DBPassword }}'
      become: yes
    
    - name: Настройка Zabbix сервера
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: '^# DBHost='
        line: 'DBHost=localhost'
      become: yes

    - name: Перезапуск Zabbix сервера и агента
      service:
        name: "{{ item }}"
        state: restarted
      loop:
        - zabbix-server
        - zabbix-agent

    - name: Перезапуск Apache
      service:
        name: apache2
        state: restarted
      become: yes
      #become_user: root
