---
- ansible.builtin.import_playbook: playbooks/playbook-zabbix-server-70-nginx-mysql.yml
- ansible.builtin.import_playbook: playbooks/playbook-zabbix-server-add-grafana.yml
- ansible.builtin.import_playbook: playbooks/playbook-zabbix-server-grafana-advanced.yml
