---
- hosts: zabbix_servers
  become: yes
  tasks:
    - name: Update packages
      apt:
        update_cache: yes

    - name: Add GPG key for Grafana
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Add Grafana apt_repository
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present

    - name: Install Grafana
      apt:
        name: grafana
        state: present

    - name: Install plunin Zabbix for Grafana
      grafana_plugin:
        name: alexanderzobnin-zabbix-app
        state: present

    - name: Start service for Grafana
      service:
        name: grafana-server
        state: started
        enabled: yes

    - name: Await starting Grafana
      wait_for:
        host: 127.0.0.1
        port: 3000
        delay: 10
        timeout: 60
        state: started

    - name: Setting up Zabbix in Grafana
      uri:
        url: "http://localhost:3000/api/datasources"
        method: POST
        user: "admin"
        password: "admin"
        body_format: json
        headers:
          Content-Type: "application/json"
        body: |
          {
            "name": "Zabbix",
            "type": "alexanderzobnin-zabbix-datasource",
            "url": "http://{{ zabbix_server_ip }}/zabbix",
            "access": "proxy",
            "basicAuth": false,
            "jsonData": {
              "username": "{{ zabbix_user }}",
              "password": "{{ zabbix_password }}"
            }
          }
        status_code: 200
      ignore_errors: yes 

    - name: Change defualt password for Grafana
      uri:
        url: "http://localhost:3000/api/admin/passwords"
        method: POST
        user: "admin"
        password: "admin"
        body_format: json
        headers:
          Content-Type: "application/json"
        body: |
          {
            "oldPassword": "admin",
            "newPassword": "{{ grafana_new_password }}"
          }
        status_code: 200

    - name: Restart Grafana
      service:
        name: grafana-server
        state: restarted
