---
- hosts: zabbix_agents
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    serverIp: 192.168.124.160

  tasks:
    - name: Update system packages
      apt:
        update_cache: yes
        name: "{{ item }}"
        state: present
      loop:
        - php
        - snmp
        - wget
        - mc
        - curl
        - nmap

    - name: Install depended packages
      apt:
        update_cache: yes

    - name: Download Zabbix Agent 6.4
      get_url:
        url: "https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb"
        dest: "/tmp/zabbix-release_6.4-1+ubuntu22.04_all.deb"

    - name: Install Zabbix Agent 6.4
      apt:
        deb: "/tmp/zabbix-release_6.4-1+ubuntu22.04_all.deb"
      register: install_zabbix_agent
      ignore_errors: yes  # ignore if it exists
    - name: Enable Zabbix agent 
      apt:
        name: zabbix-agent
        state: present

    - name: Add zabbix server ip Zabbix agent
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: 'Server={{ serverIp }}'

    - name: Setting up Zabbix агента (ServerActive)
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^# ServerActive='
        line: 'ServerActive={{ serverIp }}'

    - name: Setting up Zabbix agent (Hostname)
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Hostname='
        line: 'Hostname={{ ansible_hostname }}'

    - name: Restart Zabbix agent
      service:
        name: zabbix-agent
        state: restarted
# sudo -s
# wget https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb
# dpkg -i zabbix-release_6.4-1+ubuntu22.04_all.deb
# apt update
# apt install zabbix-agent
# systemctl restart zabbix-agent
# systemctl enable zabbix-agent