
---  
- name: Set up VPN client with strongSwan on Ubuntu 22.04
  hosts: zabbix_agents
  become: true
  vars_files:
    - ./../zabbix-agent.env
  vars:
    client_mac_address: "00:00:00:00:00:00"

  tasks:
    - name: Ensure Python3 is installed
      raw: |
        if ! command -v python3 &> /dev/null; then
          apt-get update && apt-get install -y python3
        fi
    - name: Set Python interpreter for Ansible
      ansible.builtin.set_fact:
        ansible_python_interpreter: /usr/bin/python3

    - name: Update system packages
      apt:
        update_cache: yes
        name: "{{ item }}"
        state: present
      loop:
        - strongswan
        - iptables
        - iputils-ping
        - iproute2
        - iputils-arping
        - iptables-persistent
    # get the MAC address of the client
    - name: Get MAC address of the client
      shell: ip link show eth0 | awk '/ether/ {print $2}'
      register: client_mac_address  

    - name: Create ipsec.conf for client
      copy:
        dest: /etc/ipsec.conf
        content: |
          config setup
            charondebug="ike 0, knl 0, cfg 2"

          conn myvpn
            ike=aes256-sha256-modp3072,aes128-sha256-ecp256
            esp=aes256-sha256,aes128-sha256
            keyexchange=ikev2
            leftsourceip=%config
            left=%any
            #leftsubnet=172.16.16.0/22
            leftid=client-{{ client_mac_address.stdout_lines | join('') | regex_replace(':', '-')  }}
            leftauth=psk
            right={{ server_ip }}
            rightid={{ server_ip }}
            rightauth=psk
            rightsubnet=0.0.0.0/0, 172.16.16.0/22
            dpdaction=restart
            dpddelay=15s
            dpdtimeout=60s
            auto=start
            

    - name: Create ipsec.secrets file
      copy:
        dest: /etc/ipsec.secrets
        content: |
          : PSK "{{ psk_key }}"
        mode: '0600'

    - name: Restart strongSwan service
      service:
        name: ipsec
        state: stopped
        enabled: yes
      ignore_errors: true
    
    #- name: Enable strongSwan starter service
    #  service:
    #    name: strongswan-starter
    #    state: restarted
    #    enabled: yes
    
    #- name: Add route to the server 
    #  command: sudo ip route add 172.16.16.0/22 dev eth0
    #  become: true
    #  ignore_errors: true
    
