---
- name: Set up VPN client with strongSwan on Ubuntu 22.04
  hosts: zabbix_agents
  become: yes
  vars_files:
    - ./../zabbix-agent.env
  tasks:

    - name: Install strongSwan and dependencies
      apt:
        name: strongswan
        state: present
        update_cache: yes

    - name: Create ipsec.conf for client
      copy:
        dest: /etc/ipsec.conf
        content: |
          config setup
            charondebug="ike 0, knl 0, cfg 2"

          conn myvpn
            keyexchange=ikev2
            leftsourceip=%config
            left=%any
            leftauth=psk
            right={{ server_ip }}
            rightid={{ server_ip }}
            rightauth=psk
            auto=start
            dpdaction=restart
            dpddelay=3s
            dpdtimeout=9s
            rekey=yes
            keyingtries=%forever
            mobike=no

    - name: Create ipsec.secrets file
      copy:
        dest: /etc/ipsec.secrets
        content: |
          : PSK "{{ psk_key }}"
        mode: '0600'

    - name: Restart strongSwan service
      service:
        name: ipsec
        state: restarted
        enabled: yes

    - name: Enable IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present

    - name: Apply sysctl changes
      command: sysctl -p
