---
- name: Set up VPN with strongSwan on Ubuntu 22.04
  hosts: zabbix_servers
  become: true
  vars_files:
    - ./../zabbix-server.env
  tasks:

    - name: Install strongSwan and dependencies
      apt:
        name: strongswan
        state: present
        update_cache: yes

    - name: Create ipsec.conf
      copy:
        dest: /etc/ipsec.conf
        content: |
          config setup
            charondebug="ike 2, knl 2, net 2, enc 2, cfg 2"

          conn %default
            keyexchange=ikev3
            ikelifetime=61m
            lifetime=20m
            rekeymargin=3m
            keyingtries=%forever
            authby=psk
            mobike=yes
            dpdaction=restart
            dpddelay=3s
            dpdtimeout=9s
            rekey=yes

          conn myvpn
            left={{ server_ip }}
            leftid={{ server_ip }}
            leftsubnet={{ server_ip }}/32
            leftauth=psk
            right=%any
            rightauth=psk
            rightsourceip={{ ipsec_clients_subnet }}
            auto=add
            mobike=yes
            keep_alive=10s

    - name: Create ipsec.secrets file
      copy:
        dest: /etc/ipsec.secrets
        content: |
          : PSK "{{ psk_key }}"
        mode: '0600'



    - name: Enable IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present

    - name: Apply sysctl changes
      command: sysctl -p

    - name: Restart strongSwan service
      service:
        name: ipsec
        state: restarted
        enabled: yes